

spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.254.128:3300/user
     username: xwh
     password: 123456

   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true